extends CanvasLayer
## In-game HUD, Xianxia styled.
##
## - Top-left: cultivation realm on a jade plaque (calligraphy glyphs, seal
##   stamp) and a radial jade qi gauge bound to QiSystem (smoothly animated,
##   pulses when full, flashes red when depleted).
## - Top-right: shichen sundial that turns with WorldClock.time_of_day,
##   showing the current Chinese double-hour and a sun/moon icon.
## - Bottom: key-hint scroll that fades after a few seconds (F1 brings it back).
## - Centre: `toast(text)` notifications on an unrolling scroll.
## - Full-screen ink-wash vignette.
##
## Art is generated by tools/blender/gen_ui_textures.py; styling lives in the
## shared Theme at assets/ui/xianxia_theme.tres.

const XianxiaFonts := preload("res://scripts/ui/xianxia_fonts.gd")

## Glyphs per GameState.Realm, written vertically on the jade plaque.
const REALM_GLYPHS := ["凡人", "炼气", "筑基", "金丹", "元婴"]

## The twelve double-hours (shichen): earthly branch + pinyin. Branch i is
## centred on hour 2*i (Zi = 23:00-01:00, Wu = 11:00-13:00).
const SHICHEN := [
	["子", "Zǐ"], ["丑", "Chǒu"], ["寅", "Yín"], ["卯", "Mǎo"],
	["辰", "Chén"], ["巳", "Sì"], ["午", "Wǔ"], ["未", "Wèi"],
	["申", "Shēn"], ["酉", "Yǒu"], ["戌", "Xū"], ["亥", "Hài"],
]

const KEY_HINTS := [
	["WASD", "Move"], ["Space", "Jump · Leap"], ["Shift", "Sprint"],
	["Ctrl", "Glide"], ["C", "Switch cultivator"], ["V", "Customise"],
	["Esc", "Mouse"], ["F1", "Help"],
]

const HINT_SECONDS := 8.0
const TOAST_SECONDS := 2.6
const TOAST_ROLLED_WIDTH := 84.0 ## both rollers touching (scroll margins at 0.5 scale)
const TOAST_MIN_WIDTH := 320.0
const TOAST_MAX_WIDTH := 740.0

const QI_LOW_TINT := Color(1.0, 0.62, 0.38)
const QI_FLASH_TINT := Color(1.0, 0.24, 0.18)
const BRANCH_COLOR := Color(0.1, 0.09, 0.08)
const BRANCH_ACTIVE := Color(0.78, 0.13, 0.07)

@onready var root: Control = $Root
@onready var qi_bar: TextureProgressBar = %QiBar
@onready var qi_label: Label = %QiLabel
@onready var realm_label: Label = %RealmLabel
@onready var time_label: Label = %TimeLabel
@onready var realm_glyphs: Label = %RealmGlyphs
@onready var qi_gauge: Control = %QiGauge
@onready var qi_glow: TextureRect = %QiGlow
@onready var dial_root: Control = %DialRoot
@onready var shichen_label: Label = %ShichenLabel
@onready var sun_icon: TextureRect = %SunIcon
@onready var moon_icon: TextureRect = %MoonIcon
@onready var key_hints: Control = %KeyHints
@onready var hint_paper: NinePatchRect = %HintPaper
@onready var hint_row: HBoxContainer = %HintRow
@onready var hint_sword: TextureRect = %HintSword
@onready var toast_root: Control = %Toast
@onready var toast_paper: NinePatchRect = %ToastPaper
@onready var toast_label: Label = %ToastLabel
@onready var cloud_left: TextureRect = %CloudLeft
@onready var cloud_right: TextureRect = %CloudRight
@onready var corner_tl: TextureRect = %ToastCornerTL
@onready var corner_br: TextureRect = %ToastCornerBR

var _qi_target := 100.0
var _qi_max := 100.0
var _qi_shown := 100.0
var _flash := 0.0 ## 1 right after qi runs out, decays to 0
var _bloom := 0.0 ## 1 right after qi refills, decays to 0
var _glow := 0.0
var _clock := 0.0
var _gauge_home := Vector2.ZERO
var _branch_labels: Array[Label] = []
var _branch := -1
var _hint_tween: Tween
var _toast_tween: Tween
var _toast_queue: Array = []
var _toast_busy := false
var _realm_ready := false

func _ready() -> void:
	XianxiaFonts.apply(root.theme)
	_gauge_home = qi_gauge.position
	_build_dial()
	_build_key_hints()
	toast_root.visible = false

	QiSystem.qi_changed.connect(_on_qi_changed)
	if QiSystem.has_signal("qi_depleted"):
		QiSystem.qi_depleted.connect(_on_qi_depleted)
	if QiSystem.has_signal("qi_restored_full"):
		QiSystem.qi_restored_full.connect(_on_qi_restored_full)
	GameState.realm_changed.connect(_on_realm_changed)

	_on_qi_changed(QiSystem.current_qi, QiSystem.max_qi)
	_qi_shown = _qi_target
	qi_bar.value = _qi_shown
	_on_realm_changed(GameState.realm)
	_realm_ready = true
	_update_clock(1.0)
	show_key_hints()

func _process(delta: float) -> void:
	_clock += delta
	_update_qi(delta)
	_update_clock(delta)

func _unhandled_input(event: InputEvent) -> void:
	var pressed := false
	if InputMap.has_action("show_help"):
		pressed = event.is_action_pressed("show_help")
	elif event is InputEventKey:
		var key := event as InputEventKey
		pressed = key.pressed and not key.echo and key.keycode == KEY_F1
	if pressed:
		toggle_key_hints()
		get_viewport().set_input_as_handled()

# --- public API ---------------------------------------------------------------

## Shows `text` on an unrolling scroll in the upper centre of the screen for
## `duration` seconds. Calls made while a toast is showing are queued.
func toast(text: String, duration: float = TOAST_SECONDS) -> void:
	if text.strip_edges().is_empty():
		return
	_toast_queue.append([text, maxf(duration, 0.2)])
	if not _toast_busy:
		_next_toast()

## Brings the key-hint scroll back; it fades again after `duration` seconds
## (pass 0 to keep it up until hide_key_hints()).
func show_key_hints(duration: float = HINT_SECONDS) -> void:
	if _hint_tween:
		_hint_tween.kill()
	key_hints.visible = true
	_hint_tween = create_tween()
	_hint_tween.tween_property(key_hints, "modulate:a", 1.0, 0.35)
	if duration > 0.0:
		_hint_tween.tween_interval(duration)
		_hint_tween.tween_property(key_hints, "modulate:a", 0.0, 1.4)
		_hint_tween.tween_callback(key_hints.hide)

func hide_key_hints() -> void:
	if _hint_tween:
		_hint_tween.kill()
	_hint_tween = create_tween()
	_hint_tween.tween_property(key_hints, "modulate:a", 0.0, 0.5)
	_hint_tween.tween_callback(key_hints.hide)

func toggle_key_hints() -> void:
	if key_hints.visible and key_hints.modulate.a > 0.5:
		hide_key_hints()
	else:
		show_key_hints()

## Current double-hour for a 0..24 time: [branch glyph, pinyin, index].
static func shichen_for(time_of_day: float) -> Array:
	var idx := int(floor(fposmod(time_of_day + 1.0, 24.0) / 2.0)) % 12
	return [SHICHEN[idx][0], SHICHEN[idx][1], idx]

# --- qi gauge -----------------------------------------------------------------

func _on_qi_changed(current: float, max_qi: float) -> void:
	_qi_target = current
	_qi_max = maxf(max_qi, 0.001)
	qi_bar.max_value = _qi_max
	qi_label.text = "%d / %d" % [int(round(current)), int(round(max_qi))]

func _on_qi_depleted() -> void:
	_flash = 1.0

func _on_qi_restored_full() -> void:
	_bloom = 1.0

func _update_qi(delta: float) -> void:
	# Exponential ease toward the real value: smooth, frame-rate independent,
	# and never lags behind the continuous drain/regen QiSystem emits.
	_qi_shown = lerpf(_qi_shown, _qi_target, 1.0 - exp(-10.0 * delta))
	if absf(_qi_shown - _qi_target) < 0.02:
		_qi_shown = _qi_target
	qi_bar.value = _qi_shown

	var ratio := _qi_target / _qi_max
	var tint := Color.WHITE.lerp(QI_LOW_TINT, clampf((0.3 - ratio) / 0.3, 0.0, 1.0))
	qi_bar.tint_progress = tint.lerp(QI_FLASH_TINT, _flash)
	qi_bar.tint_under = Color.WHITE.lerp(Color(1.0, 0.55, 0.5), _flash * 0.8)

	var want := 0.0
	if ratio >= 0.999:
		want = 0.32 + 0.22 * sin(_clock * 2.4)
	_glow = lerpf(_glow, want, 1.0 - exp(-5.0 * delta))
	var glow_col := Color.WHITE.lerp(QI_FLASH_TINT, _flash)
	glow_col.a = clampf(maxf(_glow + _bloom * 0.7, _flash * 0.9), 0.0, 1.0)
	qi_glow.modulate = glow_col
	qi_glow.scale = Vector2.ONE * (1.0 + 0.12 * _bloom)

	if _flash > 0.0:
		var shake := 3.0 * _flash
		qi_gauge.position = _gauge_home + Vector2(randf_range(-shake, shake), randf_range(-shake, shake))
	else:
		qi_gauge.position = _gauge_home
	_flash = move_toward(_flash, 0.0, delta * 1.4)
	_bloom = move_toward(_bloom, 0.0, delta * 1.2)

# --- realm --------------------------------------------------------------------

func _on_realm_changed(_new_realm) -> void:
	realm_label.text = GameState.realm_name()
	var idx := int(GameState.realm)
	var glyphs: String = REALM_GLYPHS[idx] if idx >= 0 and idx < REALM_GLYPHS.size() else "修仙"
	realm_glyphs.text = "\n".join(glyphs.split(""))
	if _realm_ready:
		_bloom = 1.0
		toast("突破 · %s" % GameState.realm_name())

# --- shichen sundial ----------------------------------------------------------

func _build_dial() -> void:
	var radius := dial_root.size.x * 0.5 * (200.0 / 256.0) # centre of the paper band
	var centre := dial_root.size * 0.5
	for i in SHICHEN.size():
		var l := Label.new()
		l.theme_type_variation = &"DialGlyph"
		l.text = SHICHEN[i][0]
		l.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
		l.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
		l.mouse_filter = Control.MOUSE_FILTER_IGNORE
		l.size = Vector2(26, 26)
		l.pivot_offset = l.size * 0.5
		var a := deg_to_rad(i * 30.0)
		l.position = centre + Vector2(sin(a), -cos(a)) * radius - l.size * 0.5
		l.rotation = a
		dial_root.add_child(l)
		_branch_labels.append(l)

func _update_clock(delta: float) -> void:
	var t: float = WorldClock.time_of_day
	# 15 degrees per hour; the current hour always sits under the top pointer.
	dial_root.rotation = -deg_to_rad(t * 15.0)
	var sc := shichen_for(t)
	if sc[2] != _branch:
		_branch = sc[2]
		shichen_label.text = "%s时" % sc[0]
		for i in _branch_labels.size():
			_branch_labels[i].add_theme_color_override("font_color", BRANCH_ACTIVE if i == _branch else BRANCH_COLOR)
	var hour := int(t)
	var minute := int((t - hour) * 60.0)
	time_label.text = "%s · %02d:%02d" % [sc[1], hour, minute]

	var night := 1.0 if WorldClock.is_night() else 0.0
	var k := 1.0 - exp(-3.0 * delta)
	moon_icon.modulate.a = lerpf(moon_icon.modulate.a, night, k)
	sun_icon.modulate.a = lerpf(sun_icon.modulate.a, 1.0 - night, k)

# --- key hints ----------------------------------------------------------------

func _build_key_hints() -> void:
	for hint in KEY_HINTS:
		var item := HBoxContainer.new()
		item.mouse_filter = Control.MOUSE_FILTER_IGNORE
		item.add_theme_constant_override("separation", 5)
		var cap := PanelContainer.new()
		cap.theme_type_variation = &"KeyCap"
		cap.mouse_filter = Control.MOUSE_FILTER_IGNORE
		cap.size_flags_vertical = Control.SIZE_SHRINK_CENTER
		cap.custom_minimum_size = Vector2(30, 26) # keep >= the 9-slice margins
		var key := Label.new()
		key.theme_type_variation = &"KeyLabel"
		key.text = hint[0]
		key.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
		cap.add_child(key)
		var desc := Label.new()
		desc.theme_type_variation = &"InkLabel"
		desc.text = hint[1]
		desc.size_flags_vertical = Control.SIZE_SHRINK_CENTER
		item.add_child(cap)
		item.add_child(desc)
		hint_row.add_child(item)
	_fit_key_hints.call_deferred()

func _fit_key_hints() -> void:
	var w := hint_row.get_combined_minimum_size().x + 164.0
	key_hints.offset_left = -w * 0.5
	key_hints.offset_right = w * 0.5
	var h := key_hints.offset_bottom - key_hints.offset_top
	hint_paper.size = Vector2(w, h) * 2.0
	hint_sword.position.x = w - 50.0 - hint_sword.size.x

# --- toast --------------------------------------------------------------------

func _next_toast() -> void:
	if _toast_queue.is_empty():
		_toast_busy = false
		return
	_toast_busy = true
	var item: Array = _toast_queue.pop_front()
	toast_label.text = item[0]
	var full := clampf(toast_label.get_minimum_size().x + 190.0, TOAST_MIN_WIDTH, TOAST_MAX_WIDTH)
	toast_label.modulate.a = 0.0
	corner_tl.modulate.a = 0.0
	corner_br.modulate.a = 0.0
	toast_root.modulate.a = 0.0
	toast_root.visible = true
	_set_toast_width(TOAST_ROLLED_WIDTH)

	if _toast_tween:
		_toast_tween.kill()
	_toast_tween = create_tween()
	_toast_tween.tween_property(toast_root, "modulate:a", 1.0, 0.2)
	_toast_tween.tween_method(_set_toast_width, TOAST_ROLLED_WIDTH, full, 0.6) \
		.set_trans(Tween.TRANS_CUBIC).set_ease(Tween.EASE_OUT)
	_toast_tween.tween_property(toast_label, "modulate:a", 1.0, 0.3)
	_toast_tween.parallel().tween_property(corner_tl, "modulate:a", 0.9, 0.3)
	_toast_tween.parallel().tween_property(corner_br, "modulate:a", 0.9, 0.3)
	_toast_tween.tween_interval(item[1])
	_toast_tween.tween_property(toast_label, "modulate:a", 0.0, 0.25)
	_toast_tween.parallel().tween_property(corner_tl, "modulate:a", 0.0, 0.25)
	_toast_tween.parallel().tween_property(corner_br, "modulate:a", 0.0, 0.25)
	_toast_tween.tween_method(_set_toast_width, full, TOAST_ROLLED_WIDTH, 0.45) \
		.set_trans(Tween.TRANS_CUBIC).set_ease(Tween.EASE_IN)
	_toast_tween.tween_property(toast_root, "modulate:a", 0.0, 0.25)
	_toast_tween.tween_callback(_finish_toast)

func _finish_toast() -> void:
	toast_root.visible = false
	_next_toast()

func _set_toast_width(w: float) -> void:
	toast_root.offset_left = -w * 0.5
	toast_root.offset_right = w * 0.5
	var h := toast_root.offset_bottom - toast_root.offset_top
	toast_paper.size = Vector2(w, h) * 2.0
	cloud_left.position.x = -cloud_left.size.x + 14.0
	cloud_right.position.x = w - 14.0
	corner_tl.position = Vector2(46.0, 12.0)
	corner_br.position = Vector2(w - 46.0 - corner_br.size.x, h - 12.0 - corner_br.size.y)
